environment:
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  PYTHON: "C:\\Python37-x64"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    #- TOXENV: py37
    #- TOXENV: pygtkui
    - PYTHON_VERSION: "3.7.x"

pull_requests:
  do_not_increment_build_number: true

install:
  # If there is a newer build queued for same PR, cancel this one. Credit: JuliaLang devs
  - ps:
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
      throw "There are newer queued builds for this pull request, failing early." }
  - ps: Start-FileDownload 'https://github.com/doadin/DelugeBuildFromSource/releases/download/1.0/libtorrent.pyd'
  - ps: Start-FileDownload 'https://github.com/doadin/DelugeBuildFromSource/releases/download/1.0/gvsbuild-vs15-x64.tar.gz'
  - ps: Start-FileDownload 'https://github.com/doadin/DelugeBuildFromSource/raw/master/deluge.spec'
  - copy libtorrent.pyd "C:\Python37-x64\lib\site-packages\libtorrent.pyd"
  - 7z e gvsbuild-vs15-x64.tar.gz -o"C:\gtk-build\gtk\x64\"
  - 7z x c:\gtk-build\gtk\x64\gvsbuild-vs15-x64.tar -y -o"C:\gtk-build\gtk\x64\"
  - dir c:\gtk-build\gtk\x64\
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\gtk-build\\gtk\\x64\\release\\bin;%PATH%"
  - "python -VV"
  - python -m pip install "https://github.com/doadin/DelugeBuildFromSource/releases/download/1.0/Twisted-19.10.0.dev0-cp37-cp37m-win_amd64.whl"
  - python -m pip install "C:\gtk-build\gtk\x64\release\python\pycairo-1.18.2-cp37-cp37m-win_amd64.whl"
  - python -m pip install "C:\gtk-build\gtk\x64\release\python\PyGObject-3.34.0-cp37-cp37m-win_amd64.whl"
  - if defined TOXENV (
    python -m pip install tox tox_venv
    ) else (
    python -m pip install -r requirements.txt pygame pyinstaller
    )
  - "SET PATH=C:\\OpenSSL-v11-Win64\\bin;%PATH%"
  - openssl version -v
  - 'python -c "import libtorrent; print(libtorrent.__version__)"'
  - echo "" > C:\Python37-x64\Lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_twisted.py

cache:
  - '%LOCALAPPDATA%\pip\cache'

build: false

test_script:
  - if defined TOXENV tox

after_test:
 - if not defined TOXENV python setup.py build && python setup.py install
 - cd %APPVEYOR_BUILD_FOLDER%\\packaging\\win32
 - if not defined TOXENV pyinstaller --clean --noconfirm --distpath=./build-win32 deluge.spec
 - python generate-nsh.py
 - if not defined TOXENV 7z a deluge-win.zip %APPVEYOR_BUILD_FOLDER%\\packaging\\win32\\build-win32
 - "SET PATH=C:\\Program Files (x86)\\NSIS;%PATH%"
 - if not defined TOXENV makensis deluge-win32-installer.nsi

artifacts:
 - path: packaging\win32\deluge-win.zip
 - path: packaging\win32\build\*.exe

on_success:

