name: Package

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: "Enter a tag or commit to package"
        default: ""

jobs:
  windows_package:
    runs-on: windows-2022
    timeout-minutes: 30
    if: (github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'package'))
    strategy:
      matrix:
        arch: [x64]
        python: ["3.10"]
        libtorrent: [2.0.7, 1.2.19]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Checkout Deluge source to subdir to enable packaging any tag/commit
      - name: Checkout Deluge source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          path: deluge_src

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python}}
          architecture: ${{ matrix.arch }}
          cache: pip

      - name: Prepare pip
        run: python -m pip install wheel setuptools==68.*

      - name: Install GTK
        run: |
          $WebClient = New-Object System.Net.WebClient
          $WebClient.DownloadFile("https://github.com/deluge-torrent/gvsbuild-release/releases/download/latest/gvsbuild-py${{ matrix.python }}-vs16-${{ matrix.arch }}.zip","C:\GTK.zip")
          7z x C:\GTK.zip -oc:\GTK
          echo "C:\GTK\release\lib" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\GTK\release\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\GTK\release" | Out-File -FilePath $env:GITHUB_PATH -Append
          python -m pip install --no-index --find-links="C:\GTK\release\python" pycairo PyGObject
      - name: Download Twisted wheel artifact
        shell: pwsh
        run: |
          $url = "https://productionresultssa0.blob.core.windows.net/actions-results/2f46cc44-b7f8-401f-b75d-d3d8581efda7/workflow-job-run-9b7c8e33-5bdd-5798-812b-56365bbfc035/artifacts/f99d7c6c289929169d69519d7ef52b8b85f5d7b28955db9d79cb5fa87007e590.zip?rscd=attachment%3B+filename%3D%22twisted-wheel-py3.10-x64.zip%22&se=2026-02-09T07%3A31%3A21Z&sig=iv06YRu3DKIg7oJ%2FNq4IJGG%2F9D3Xv%2B3AAR%2FCikG6ADw%3D&ske=2026-02-09T09%3A47%3A38Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2026-02-09T05%3A47%3A38Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2026-02-09T07%3A21%3A16Z&sv=2025-11-05"
          $headers = @{ Authorization = "Bearer ${{ secrets.GITHUB_TOKEN }}" }
          Invoke-WebRequest -Uri $url -Headers $headers -OutFile twisted_artifact.zip

      - name: Extract Twisted wheel
        run: |
          mkdir twisted-wheel
          tar -xf twisted_artifact.zip -C twisted-wheel

      - name: Install Twisted wheel
        run: pip install twisted-wheel/*.whl

      - name: Install Python dependencies
        # Pillow no longer provides 32-bit wheels for Windows
        # so specify only-binary to install old version.
        run: >
          python -m pip install
          --only-binary=pillow
          twisted[tls]==22.8.0
          libtorrent==${{ matrix.libtorrent }}
          pyinstaller
          pygame
          -r requirements.txt

      - name: Install Deluge
        working-directory: deluge_src
        run: |
          python -m pip install .
          python setup.py install_scripts

      - name: Freeze Deluge
        working-directory: packaging/win
        run: |
          pyinstaller --clean delugewin.spec --distpath freeze

      - name: Verify Deluge exes
        working-directory: packaging/win/freeze/Deluge/
        run: |
          deluge-debug.exe -v
          deluged-debug.exe -v
          deluge-web-debug.exe -v
          deluge-console -v

      - name: Make Deluge Installer
        working-directory: ./packaging/win
        run: |
          python setup_nsis.py
          makensis /Darch=${{ matrix.arch }} deluge-win-installer.nsi

      - uses: actions/upload-artifact@v4
        with:
          name: deluge-py${{ matrix.python }}-lt${{ matrix.libtorrent }}-${{ matrix.arch }}
          path: packaging/win/*.exe
